const CustomerOrders = require("../models/customerOrders");
const DesignerOrders = require("../models/designerOrders");
const Users = require("../models/users");
const Products = require("../models/products");

exports.placeOrder = async (req, res) => {
  let {
    orderedProducts,
    total,
    billingDetails,
    saveDetails,
    paymentMethod
  } = req.body;

  let customerOrderId;
  //Here we will create the order of the customer
  await CustomerOrders.create({
    products: orderedProducts,
    customerId: req.user.id,
    total: total
  })
    .then(order => {
      customerOrderId = order._id;

    })
    .catch(err =>
      console.log(err)
    );

  orderedProducts.map(orderProduct => {
    // console.log(orderProduct);

    DesignerOrders.create({
      product: orderProduct.productId._id,
      price: orderProduct.price,
      color: orderProduct.color,
      size: orderProduct.size,
      discount: orderProduct.discount,
      status: "Active",
      customer: req.user.id,
      designer: orderProduct.productId.userId,
      customerOrderId: customerOrderId,
      "billingDetails.firstName": billingDetails.firstName,
      "billingDetails.lastName": billingDetails.lastName,
      "billingDetails.province": billingDetails.province,
      "billingDetails.streetAddress": billingDetails.streetAddress,
      "billingDetails.city": billingDetails.city,
      "billingDetails.zipcode": billingDetails.zipcode,
      "billingDetails.country": billingDetails.country,
      "billingDetails.phone": billingDetails.phone,
      paymentMethod: paymentMethod
    })
      .then(order =>
        console.log("Designer Order created successfully")
      )
      .catch(err =>
        console.log(err)
      );
  });

  if (saveDetails) {
    Users.findByIdAndUpdate(req.user.id, {
      cart: [],
      firstName: billingDetails.firstName,
      lastName: billingDetails.lastName,
      province: billingDetails.province,
      streetAddress: billingDetails.streetAddress,
      city: billingDetails.city,
      zipcode: billingDetails.zipcode,
      country: billingDetails.country,
      phone: billingDetails.phone
    })
      .lean()
      .then(user =>
        res
          .status(200)
          .json({ message: "Order Placed Successfully", success: true })
      )
      .catch(err =>
        res
          .status(400)
          .json({ message: "Something went wrong", success: false })
      );
  } else {
    Users.findByIdAndUpdate(req.user.id, { cart: [] })
      .lean()
      .then(user =>
        res
          .status(200)
          .json({ message: "Order Placed Successfully", success: true })
      )
      .catch(err =>
        res
          .status(400)
          .json({ message: "Something went wrong", success: false })
      );
  }
};

exports.fetchCustomerOrders = (req, res) => {
  CustomerOrders.find({ customerId: req.user.id })
    .select("products")
    .lean()
    .then(orders =>
      res.status(200).json({
        orders: orders,
        success: true,
        message: "Customer Orders Fetched Successfully"
      })
    )
    .catch(err =>
      res.status(400).json({ message: "Something went wrong", success: false })
    );
};

exports.fetchDesignerOrders = (req, res) => {
  DesignerOrders.find({ designer: req.user.id })
    .lean()
    .sort({ status: "asc" })
    .then(orders =>
      res.status(200).json({
        orders: orders,
        success: true,
        message: "Customer Orders Fetched Successfully"
      })
    )
    .catch(err =>
      res.status(400).json({ message: "Something went wrong", success: false })
    );
};

/**
 * Required Parameters (orderId, productId)
 * orderId = CustomerOrders._id
 * productId = CustomerOrders.products._id (It is the autogenerated key for every product in the array of the products)
 */
exports.cancelOrderProductByCustomer = (req, res) => {
  CustomerOrders.findOne({
    customerId: req.user.id,
    _id: req.body.orderId
  })
    .select("products")
    .then(order => {
      console.log(order.products);
    })
    .catch(err => console.log(err));
};
